defaults: &defaults
  adapter: postgresql
  host: localhost
  username: postgres

development:
  database: wedding_development
  password: password
  <<: *defaults

test:
  database: wedding_test
  password: password
  <<: *defaults

